"""Installer test in a throwaway HOME with a fake `claude` binary. Never touches real configs."""
import json, os, stat, subprocess, sys, tempfile
home = tempfile.mkdtemp()
bindir = os.path.join(home, "bin"); os.makedirs(bindir)
log = os.path.join(home, "claude.log")
fake = os.path.join(bindir, "claude")
open(fake, "w").write(f'#!/bin/sh\necho "$@" >> {log}\n'); os.chmod(fake, 0o755)
for d in (".gemini", ".codex", ".cursor", ".config/Claude", ".config/zed"):
    os.makedirs(os.path.join(home, d))
open(os.path.join(home, ".gemini/settings.json"), "w").write('{"security": {"x": 1}}')
open(os.path.join(home, ".codex/config.toml"), "w").write('model = "x"\n\n[desktop]\na = 1\n')
open(os.path.join(home, ".config/zed/settings.json"), "w").write('// comment\n{"theme": "One"}\n')
env = dict(os.environ, HOME=home, PATH=bindir + ":/usr/bin:/bin")
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
def run(*a):
    return subprocess.run([sys.executable, "-m", "deckhand", "mcp", *a], cwd=ROOT, env=env, capture_output=True, text=True)
fails = []
def check(n, c, x=""):
    print(("ok   " if c else "FAIL ") + n + ("" if c else "  " + x)); (None if c else fails.append(n))
r = run("status"); check("status lists clients", "claude-code" in r.stdout and "gemini" in r.stdout, r.stdout + r.stderr)
r = run("install"); print(r.stdout, r.stderr)
check("install exit nonzero only because zed has comments", "Zed" in r.stdout and "FAIL" in r.stdout and "Gemini CLI: Added" in r.stdout)
g = json.load(open(os.path.join(home, ".gemini/settings.json")))
check("gemini merged, existing keys kept", g["security"] == {"x": 1} and g["mcpServers"]["deckhand"]["args"] == ["mcp"])
check("gemini backup made", os.path.exists(os.path.join(home, ".gemini/settings.json.deckhand-backup")))
t = open(os.path.join(home, ".codex/config.toml")).read()
check("codex toml block added, existing kept", "[mcp_servers.deckhand]" in t and "[desktop]" in t and 'model = "x"' in t, t)
check("cursor created", "deckhand" in json.load(open(os.path.join(home, ".cursor/mcp.json")))["mcpServers"])
check("claude code via CLI", "mcp add --scope user deckhand --" in open(log).read(), open(log).read())
check("zed comments file untouched", open(os.path.join(home, ".config/zed/settings.json")).read().startswith("// comment"))
run("install")
t = open(os.path.join(home, ".codex/config.toml")).read()
check("idempotent codex", t.count("[mcp_servers.deckhand]") == 1)
r = run("status"); check("status shows connected", "connected" in r.stdout)
r = run("uninstall")
t = open(os.path.join(home, ".codex/config.toml")).read()
g = json.load(open(os.path.join(home, ".gemini/settings.json")))
check("uninstall cleans codex+gemini", "mcp_servers.deckhand" not in t and "[desktop]" in t and "deckhand" not in g.get("mcpServers", {}), t)
r = run("config"); check("config prints snippet", '"mcpServers"' in r.stdout and "deckhand" in r.stdout)
print("FAILED:", fails if fails else "none"); sys.exit(1 if fails else 0)
